steps:
  - name: gcr.io/cloud-builders/gsutil
    id: Sync the frontend repo
    args: ['-m', 'rsync', '-r', '-c', '-d', '.', 'gs://crc-frontend-bucket']
  - name: gcr.io/cloud-builders/gcloud
    id:  Invalidate Cloud CDN cached content
    args: ['compute', 'url-maps', 'invalidate-cdn-cache', '$_LOAD_BALANCER_NAME', '--path', '$_URL_PATH']
